version: '3.8'

networks:
  arkvote_network:
    driver: bridge

services:
  mongodb:
    image: docker.io/mongo:7.0
    container_name: arkvote_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: arkvote
      MONGO_INITDB_ROOT_PASSWORD: arkvote_password
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - arkvote_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/redis:7-alpine
    container_name: arkvote_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - arkvote_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: docker.io/nats:2.10-alpine
    container_name: arkvote_nats
    restart: unless-stopped
    command: "-js -sd /data"
    volumes:
      - ./data/nats:/data
    networks:
      - arkvote_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 10s
      timeout: 5s
      retries: 5

  ark-vote:
    build:
      context: .
      dockerfile: Dockerfile
    image: arkvote:latest
    container_name: arkvote_app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=docker
      - WORKER_COUNT=4
    volumes:
      - ./character_table.json:/app/character_table.json
      - ./docker_config:/app/config
      - ./logs:/app/logs
    networks:
      - arkvote_network
    # command: ["web-server"]
    command: ["sh", "-c", "for i in $(seq 1 $WORKER_COUNT); do ./ark-vote web-server & done; wait"]

  nats-consumer:
    image: arkvote:latest
    container_name: arkvote_nats_consumer
    restart: unless-stopped
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - APP_ENV=docker
    user: "0"
    volumes:
      - ./docker_config:/app/config
    networks:
      - arkvote_network
    command: ["nats-consumer"]
