global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'arknights-vote'
    static_configs:
      - targets: ['127.0.0.1:3000']
        labels:
          app: "arknights-vote"
          prefix: "vote"