name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain
        with:
          toolchain: stable

      - name: Build with cargo
        run: cargo build --release

      - name: Set binary name
        id: bin
        run: |
          echo "name=ark-vote" >> $GITHUB_OUTPUT

      - name: Rename output binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Rename-Item target/release/${{ steps.bin.outputs.name }} target/release/${{ steps.bin.outputs.name }}.exe

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.bin.outputs.name }}-${{ matrix.os }}
          path: |
            target/release/${{ steps.bin.outputs.name }}*
